### ISSUE TITLE
One or more errors occurred when i run MVC3 application 

### ISSUE THREAD

**Issue by bitf09a013** [scottksmith95/CSharp.oDesk#1]
I have updated the api key and secret in the sample programs you have given but when the code reaches on the line below:

var requestToken = _oDeskProvider.OAuthOperations.FetchRequestTokenAsync(CallbackUrl, null).Result
//Un-handled exception: POST request for 'https://www.odesk.com/api/auth/v1/oauth/token/request' resulted in 503 - ServiceUnavailable (Service Unavailable).

Its not getting the request token, the console application gives the same exception when calling the same function. Any quick help please

**Comment by scottksmith95** [comment]
A 503 indicates the service is unavailable on oDesk. Are they experiencing issues?

**Comment by bitf09a013** [comment]
Hey Smith, thanks for your quick reply.
When i hit https://www.odesk.com/api/auth/v1/oauth/token/request in browser, as it is a POST so can't really tell much about the end-point. But in their api documentation, odesk has mentioned the same end-point to get the request token (here: https://developers.odesk.com/?lang=python#authentication_get-request-token). Can you please figure out what might be wrong?

**Comment by scottksmith95** [comment]
I haven't used this client in a very long time. Could you test it out using curl or Postman (great Chrome app) for API testing?
