### ISSUE TITLE
Relative URLs don't work

### ISSUE THREAD

**Issue by o-pikozh** [scottksmith95/CSharp.oDesk#2]
Please change ApiUriBase in CSharp.oDesk/Api/Impl/oDeskTemplate.cs:46 from "http://www.odesk.com/api/" to "https://www.odesk.com/api/" (i.e. http to https).

Because:
1. [oDesk API Reference](https://developers.odesk.com/#getting-started_request-structure) states that "All API requests must be made over HTTPS." and "The base URLs for all oDesk API requests are: https://www.odesk.com/api/ - main entry point, https://www.odesk.com/gds/ - an entry point for Report resources over GDS protocol".
2. Relative URLs with ApiUriBase="http://www.odesk.com/api/" don't work anymore.

Also, if it doesn't bother you of course, it'll be nice to push this fix to nuget too.

**Comment by o-pikozh** [comment]
1. [oDesk API Reference](https://developers.odesk.com/#getting-started_request-structure) states that "All API requests must be made over HTTPS." and "The base URLs for all oDesk API requests are: https://www.odesk.com/api/ - main entry point, https://www.odesk.com/gds/ - an entry point for Report resources over GDS protocol".
2. Relative URLs with ApiUriBase="http://www.odesk.com/api/" don't work anymore.

**Comment by o-pikozh** [comment]
I can make pull-request if needed.

**Comment by scottksmith95** [comment]
Please feel free to make a pull request. I will gladly accept it.

**Comment by o-pikozh** [comment]
Could you please update CSharp.oDesk package at nuget?

**Comment by scottksmith95** [comment]
Yes, I can do that but probably not until later this week.

**Comment by scottksmith95** [comment]
A new package has been published.
